### ISSUE TITLE
Why embed d6tcollect by default ?

### ISSUE THREAD

**Issue by eromoe** [d6t/d6tstack#7]
At least disable by default.

**Comment by d6tdev** [comment]
Because a lot of people don't report issues when they have problems and also without it we don't know what functions are valuable and where we should spend time improving and developing new features. If you're willing to do that please reach out to support-at-databolt.tech. We're transparent, it doesn't collect any sensitive information and it's easy to turn off.

**Comment by ca-scribner** [comment]
For what it is worth, I'm in a security environment that prevents me from using d6tflow because d6tcollect is embedded and required.
